<?php
	include "connection.php"; 
	include "navbar.php";
?>
<?php

{

$res=mysqli_query($db,"SELECT * FROM `carrenting` ORDER BY cid DESC LIMIT 1");

echo "<table class='table table-bordered table-hover'>"; echo "<tr style='background-color: #6db6b9e6;'>";
//table header


echo "<th>"; echo "Driver name"; echo "</th>"; echo "<th>"; echo "Car name"; echo "</th>"; echo "<th>"; echo "Car number"; echo "</th>";
echo "<th>"; echo "Price"; echo "</th>";

echo "<th>"; echo "Status"; echo "</th>"; echo "</tr>";
 

while($row=mysqli_fetch_assoc($res))

{

echo "<tr>";


echo "<td>"; echo $row['Driver_name']; echo "</td>"; echo "<td>"; echo $row['Car_name']; echo "</td>"; echo "<td>"; echo $row['Car_number']; echo "</td>";
echo "<td>"; echo $row['Price']; echo "</td>";

echo "<td>"; echo $row['Status']; echo "</td>"; echo "</tr>";
}

echo "</table>";

}

?>
<?php
	$apikey="rzp_test_mJBO2n8x6Aoyac";
?>

<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="500000" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="car renting system"
    data-description="Reserving the car"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="koushik"
    data-prefill.email="koushikgampa@example.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
<!--<?php $sql="SELECT Price FROM `carrenting` ORDER BY cid DESC LIMIT 1";$query=mysqli_query($db,$sql);?>*100-->